% export_zpf_reference — 阶段 B1 C++ 测试参考向量导出
% 来源：阶段 A 已验收 evidence/filter_reference_vectors.mat（91ca68b）
% 输出：紧凑文本目录 reference_vectors/，每向量一个 .txt（%.17g 逐行），
%       供 tests/ring_zero_phase_filter_test.cpp 逐样本对照（无 MATLAB 运行时依赖）。
% 运行：matlab -batch "run('export_zpf_reference.m')"（本脚本所在目录）

outdir = fullfile(fileparts(mfilename('fullpath')), 'reference_vectors');
if ~exist(outdir, 'dir'), mkdir(outdir); end

src = fullfile(fileparts(mfilename('fullpath')), '..', '..', 'evidence', ...
               'filter_reference_vectors.mat');
S = load(src);
fields = fieldnames(S);
vecFields = fields(~cellfun(@(f) isstruct(S.(f)) || ischar(S.(f)), fields));

nSaved = 0;
for k = 1:numel(vecFields)
    nm = vecFields{k};
    v = S.(nm);
    if ~isnumeric(v) || ~isvector(v), continue; end
    v = v(:);
    fid = fopen(fullfile(outdir, [nm '.txt']), 'w');
    for i = 1:numel(v)
        fprintf(fid, '%.17g\n', v(i));
    end
    fclose(fid);
    nSaved = nSaved + 1;
end

fid = fopen(fullfile(outdir, 'README.txt'), 'w');
fprintf(fid, 'source: CODEX_REPORTS/ring-zero-phase-pa-inversion-20260919/evidence/filter_reference_vectors.mat\n');
fprintf(fid, 'source commit: 91ca68b36dac9c14ccd756c52896ea20ad794e0a (stage A approved)\n');
fprintf(fid, 'generated by: stage-B1/matlab/export_zpf_reference.m, MATLAB %s\n', version);
fprintf(fid, 'convention: refZeroPhase.m (odd extension nfact=3n, per-section steady-state DF2T init, forward/backward)\n');
fprintf(fid, 'vectors: %d files, one double per line (%%.17g)\n', nSaved);
fprintf(fid, 'fs=%.17g N=%d nHP=%d nLP=%d fcHP=%.17g fcLP=%.17g\n', ...
        S.fs, S.N, S.nHP, S.nLP, S.fcHP, S.fcLP);
fclose(fid);
fprintf('saved %d vectors + README -> %s\n', nSaved, outdir);
